# Generated by Django 5.1.2 on 2024-10-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Income', models.IntegerField(primary_key='Income', serialize=False)),
                ('Interest', models.FloatField()),
                ('Duedate', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
